pipeline {
    agent any 

    environment {
        REGISTRY = 'docker.io'
        DOCKERHUB_REPO = 'orvencasido/devops-project-1'
        IMAGE = "${REGISTRY}/${DOCKERHUB_REPO}:${env.BUILD_NUMBER}"
        LATEST = "${REGISTRY}/${DOCKERHUB_REPO}:latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Test') {
            steps {
                sh '''
                    test -f index.html || { echo "index.html is missing!"; exit 1; }
                    test -f index.html || { echo "index.html is empty!"; exit 1; }
                    echo "basic test passed!
                '''
            }
        }

        stage('Build Image') {
            steps {
                sh """
                    docker build -t ${IMAGE} -t ${LATEST} .
                """
            }
        }

        stage('Push Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'USER', password Variable: 'PASS')]) {
                    sh """
                        echo "${PASS}" | docker login -u "${USER}" --password-stdin
                        docker push ${IMAGE}
                        docker push ${LATEST}
                    """
                }
            }
        }

        stage('Deploy') {
            
        }
    }
}