pipeline {
    agent any

    stages {
        stage('Sample') {
            steps {
                sh """
                    echo "Hello, Jenkins!"echo 
                """
            }
        }
    }
}